/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as IndexRouteImport } from './routes/index.tsx'
import { Route as AuthRouteImport } from './routes/_auth.tsx'
import { Route as DashboardRouteImport } from './routes/_dashboard.tsx'
import { Route as DeviceRouteImport } from './routes/_device.tsx'
import { Route as AboutRouteImport } from './routes/about.tsx'
import { Route as WelcomeRouteImport } from './routes/welcome.tsx'
import { Route as AuthConsentRouteImport } from './routes/_auth/consent.tsx'
import { Route as AuthPrivacyRouteImport } from './routes/_auth/privacy.tsx'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password.tsx'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in.tsx'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up.tsx'
import { Route as AuthTermsRouteImport } from './routes/_auth/terms.tsx'
import { Route as AuthTwoFactorRouteImport } from './routes/_auth/two-factor.tsx'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email.tsx'
import { Route as DashboardAdminRouteImport } from './routes/_dashboard/admin.tsx'
import { Route as DashboardConnectionsRouteImport } from './routes/_dashboard/connections.tsx'
import { Route as DeviceDeviceRouteImport } from './routes/_device/device.tsx'
import { Route as DashboardAccountIndexRouteImport } from './routes/_dashboard/account/index.tsx'
import { Route as DashboardAccountApiKeysRouteImport } from './routes/_dashboard/account/api-keys.tsx'
import { Route as DashboardAccountPasskeysRouteImport } from './routes/_dashboard/account/passkeys.tsx'
import { Route as DashboardAccountProvidersRouteImport } from './routes/_dashboard/account/providers.tsx'
import { Route as DashboardAccountSessionsRouteImport } from './routes/_dashboard/account/sessions.tsx'
import { Route as DashboardAdminIndexRouteImport } from './routes/_dashboard/admin/index.tsx'
import { Route as DashboardAdminApiKeysRouteImport } from './routes/_dashboard/admin/api-keys.tsx'
import { Route as DashboardAdminSessionsRouteImport } from './routes/_dashboard/admin/sessions.tsx'
import { Route as DashboardAdminUsersRouteImport } from './routes/_dashboard/admin/users.tsx'
import { Route as DeviceDeviceApproveRouteImport } from './routes/_device/device/approve.tsx'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$.ts'
import { Route as OrgsAcceptInvitationIdRouteImport } from './routes/orgs/accept/$invitationId.tsx'
import { Route as DashboardAdminClientsIndexRouteImport } from './routes/_dashboard/admin/clients/index.tsx'
import { Route as DashboardAdminClientsIdRouteImport } from './routes/_dashboard/admin/clients/$id.tsx'
import { Route as DashboardAdminClientsNewRouteImport } from './routes/_dashboard/admin/clients/new.tsx'
import { Route as DashboardAdminOrgsIndexRouteImport } from './routes/_dashboard/admin/orgs/index.tsx'
import { Route as DashboardAdminOrgsIdRouteImport } from './routes/_dashboard/admin/orgs/$id.tsx'
import { Route as DashboardAdminOrgsNewRouteImport } from './routes/_dashboard/admin/orgs/new.tsx'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/_device',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConsentRoute = AuthConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPrivacyRoute = AuthPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTermsRoute = AuthTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTwoFactorRoute = AuthTwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConnectionsRoute = DashboardConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => DashboardRoute,
} as any)
const DeviceDeviceRoute = DeviceDeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => DeviceRoute,
} as any)
const DashboardAccountIndexRoute = DashboardAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountApiKeysRoute = DashboardAccountApiKeysRouteImport.update({
  id: '/account/api-keys',
  path: '/account/api-keys',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountPasskeysRoute =
  DashboardAccountPasskeysRouteImport.update({
    id: '/account/passkeys',
    path: '/account/passkeys',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAccountProvidersRoute =
  DashboardAccountProvidersRouteImport.update({
    id: '/account/providers',
    path: '/account/providers',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAccountSessionsRoute =
  DashboardAccountSessionsRouteImport.update({
    id: '/account/sessions',
    path: '/account/sessions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminApiKeysRoute = DashboardAdminApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminSessionsRoute = DashboardAdminSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DeviceDeviceApproveRoute = DeviceDeviceApproveRouteImport.update({
  id: '/approve',
  path: '/approve',
  getParentRoute: () => DeviceDeviceRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsAcceptInvitationIdRoute = OrgsAcceptInvitationIdRouteImport.update({
  id: '/orgs/accept/$invitationId',
  path: '/orgs/accept/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminClientsIndexRoute =
  DashboardAdminClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminClientsIdRoute = DashboardAdminClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminClientsNewRoute =
  DashboardAdminClientsNewRouteImport.update({
    id: '/clients/new',
    path: '/clients/new',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminOrgsIndexRoute = DashboardAdminOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminOrgsIdRoute = DashboardAdminOrgsIdRouteImport.update({
  id: '/orgs/$id',
  path: '/orgs/$id',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminOrgsNewRoute = DashboardAdminOrgsNewRouteImport.update({
  id: '/orgs/new',
  path: '/orgs/new',
  getParentRoute: () => DashboardAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/welcome': typeof WelcomeRoute
  '/consent': typeof AuthConsentRoute
  '/privacy': typeof AuthPrivacyRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/terms': typeof AuthTermsRoute
  '/two-factor': typeof AuthTwoFactorRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/admin': typeof DashboardAdminRouteWithChildren
  '/connections': typeof DashboardConnectionsRoute
  '/device': typeof DeviceDeviceRouteWithChildren
  '/account/api-keys': typeof DashboardAccountApiKeysRoute
  '/account/passkeys': typeof DashboardAccountPasskeysRoute
  '/account/providers': typeof DashboardAccountProvidersRoute
  '/account/sessions': typeof DashboardAccountSessionsRoute
  '/admin/api-keys': typeof DashboardAdminApiKeysRoute
  '/admin/sessions': typeof DashboardAdminSessionsRoute
  '/admin/users': typeof DashboardAdminUsersRoute
  '/device/approve': typeof DeviceDeviceApproveRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/orgs/accept/$invitationId': typeof OrgsAcceptInvitationIdRoute
  '/account/': typeof DashboardAccountIndexRoute
  '/admin/': typeof DashboardAdminIndexRoute
  '/admin/clients/$id': typeof DashboardAdminClientsIdRoute
  '/admin/clients/new': typeof DashboardAdminClientsNewRoute
  '/admin/orgs/$id': typeof DashboardAdminOrgsIdRoute
  '/admin/orgs/new': typeof DashboardAdminOrgsNewRoute
  '/admin/clients/': typeof DashboardAdminClientsIndexRoute
  '/admin/orgs/': typeof DashboardAdminOrgsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/welcome': typeof WelcomeRoute
  '/consent': typeof AuthConsentRoute
  '/privacy': typeof AuthPrivacyRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/terms': typeof AuthTermsRoute
  '/two-factor': typeof AuthTwoFactorRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/connections': typeof DashboardConnectionsRoute
  '/device': typeof DeviceDeviceRouteWithChildren
  '/account/api-keys': typeof DashboardAccountApiKeysRoute
  '/account/passkeys': typeof DashboardAccountPasskeysRoute
  '/account/providers': typeof DashboardAccountProvidersRoute
  '/account/sessions': typeof DashboardAccountSessionsRoute
  '/admin/api-keys': typeof DashboardAdminApiKeysRoute
  '/admin/sessions': typeof DashboardAdminSessionsRoute
  '/admin/users': typeof DashboardAdminUsersRoute
  '/device/approve': typeof DeviceDeviceApproveRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/orgs/accept/$invitationId': typeof OrgsAcceptInvitationIdRoute
  '/account': typeof DashboardAccountIndexRoute
  '/admin': typeof DashboardAdminIndexRoute
  '/admin/clients/$id': typeof DashboardAdminClientsIdRoute
  '/admin/clients/new': typeof DashboardAdminClientsNewRoute
  '/admin/orgs/$id': typeof DashboardAdminOrgsIdRoute
  '/admin/orgs/new': typeof DashboardAdminOrgsNewRoute
  '/admin/clients': typeof DashboardAdminClientsIndexRoute
  '/admin/orgs': typeof DashboardAdminOrgsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_device': typeof DeviceRouteWithChildren
  '/about': typeof AboutRoute
  '/welcome': typeof WelcomeRoute
  '/_auth/consent': typeof AuthConsentRoute
  '/_auth/privacy': typeof AuthPrivacyRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_auth/terms': typeof AuthTermsRoute
  '/_auth/two-factor': typeof AuthTwoFactorRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/_dashboard/connections': typeof DashboardConnectionsRoute
  '/_device/device': typeof DeviceDeviceRouteWithChildren
  '/_dashboard/account/api-keys': typeof DashboardAccountApiKeysRoute
  '/_dashboard/account/passkeys': typeof DashboardAccountPasskeysRoute
  '/_dashboard/account/providers': typeof DashboardAccountProvidersRoute
  '/_dashboard/account/sessions': typeof DashboardAccountSessionsRoute
  '/_dashboard/admin/api-keys': typeof DashboardAdminApiKeysRoute
  '/_dashboard/admin/sessions': typeof DashboardAdminSessionsRoute
  '/_dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/_device/device/approve': typeof DeviceDeviceApproveRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/orgs/accept/$invitationId': typeof OrgsAcceptInvitationIdRoute
  '/_dashboard/account/': typeof DashboardAccountIndexRoute
  '/_dashboard/admin/': typeof DashboardAdminIndexRoute
  '/_dashboard/admin/clients/$id': typeof DashboardAdminClientsIdRoute
  '/_dashboard/admin/clients/new': typeof DashboardAdminClientsNewRoute
  '/_dashboard/admin/orgs/$id': typeof DashboardAdminOrgsIdRoute
  '/_dashboard/admin/orgs/new': typeof DashboardAdminOrgsNewRoute
  '/_dashboard/admin/clients/': typeof DashboardAdminClientsIndexRoute
  '/_dashboard/admin/orgs/': typeof DashboardAdminOrgsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/welcome'
    | '/consent'
    | '/privacy'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/two-factor'
    | '/verify-email'
    | '/admin'
    | '/connections'
    | '/device'
    | '/account/api-keys'
    | '/account/passkeys'
    | '/account/providers'
    | '/account/sessions'
    | '/admin/api-keys'
    | '/admin/sessions'
    | '/admin/users'
    | '/device/approve'
    | '/api/auth/$'
    | '/orgs/accept/$invitationId'
    | '/account/'
    | '/admin/'
    | '/admin/clients/$id'
    | '/admin/clients/new'
    | '/admin/orgs/$id'
    | '/admin/orgs/new'
    | '/admin/clients/'
    | '/admin/orgs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/welcome'
    | '/consent'
    | '/privacy'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/two-factor'
    | '/verify-email'
    | '/connections'
    | '/device'
    | '/account/api-keys'
    | '/account/passkeys'
    | '/account/providers'
    | '/account/sessions'
    | '/admin/api-keys'
    | '/admin/sessions'
    | '/admin/users'
    | '/device/approve'
    | '/api/auth/$'
    | '/orgs/accept/$invitationId'
    | '/account'
    | '/admin'
    | '/admin/clients/$id'
    | '/admin/clients/new'
    | '/admin/orgs/$id'
    | '/admin/orgs/new'
    | '/admin/clients'
    | '/admin/orgs'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_dashboard'
    | '/_device'
    | '/about'
    | '/welcome'
    | '/_auth/consent'
    | '/_auth/privacy'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_auth/terms'
    | '/_auth/two-factor'
    | '/_auth/verify-email'
    | '/_dashboard/admin'
    | '/_dashboard/connections'
    | '/_device/device'
    | '/_dashboard/account/api-keys'
    | '/_dashboard/account/passkeys'
    | '/_dashboard/account/providers'
    | '/_dashboard/account/sessions'
    | '/_dashboard/admin/api-keys'
    | '/_dashboard/admin/sessions'
    | '/_dashboard/admin/users'
    | '/_device/device/approve'
    | '/api/auth/$'
    | '/orgs/accept/$invitationId'
    | '/_dashboard/account/'
    | '/_dashboard/admin/'
    | '/_dashboard/admin/clients/$id'
    | '/_dashboard/admin/clients/new'
    | '/_dashboard/admin/orgs/$id'
    | '/_dashboard/admin/orgs/new'
    | '/_dashboard/admin/clients/'
    | '/_dashboard/admin/orgs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  DeviceRoute: typeof DeviceRouteWithChildren
  AboutRoute: typeof AboutRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  OrgsAcceptInvitationIdRoute: typeof OrgsAcceptInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_device': {
      id: '/_device'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/consent': {
      id: '/_auth/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof AuthConsentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/privacy': {
      id: '/_auth/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AuthPrivacyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/terms': {
      id: '/_auth/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof AuthTermsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/two-factor': {
      id: '/_auth/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof AuthTwoFactorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/admin': {
      id: '/_dashboard/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/connections': {
      id: '/_dashboard/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof DashboardConnectionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_device/device': {
      id: '/_device/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceDeviceRouteImport
      parentRoute: typeof DeviceRoute
    }
    '/_dashboard/account/': {
      id: '/_dashboard/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof DashboardAccountIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/account/api-keys': {
      id: '/_dashboard/account/api-keys'
      path: '/account/api-keys'
      fullPath: '/account/api-keys'
      preLoaderRoute: typeof DashboardAccountApiKeysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/account/passkeys': {
      id: '/_dashboard/account/passkeys'
      path: '/account/passkeys'
      fullPath: '/account/passkeys'
      preLoaderRoute: typeof DashboardAccountPasskeysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/account/providers': {
      id: '/_dashboard/account/providers'
      path: '/account/providers'
      fullPath: '/account/providers'
      preLoaderRoute: typeof DashboardAccountProvidersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/account/sessions': {
      id: '/_dashboard/account/sessions'
      path: '/account/sessions'
      fullPath: '/account/sessions'
      preLoaderRoute: typeof DashboardAccountSessionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/': {
      id: '/_dashboard/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/api-keys': {
      id: '/_dashboard/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof DashboardAdminApiKeysRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/sessions': {
      id: '/_dashboard/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof DashboardAdminSessionsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/users': {
      id: '/_dashboard/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_device/device/approve': {
      id: '/_device/device/approve'
      path: '/approve'
      fullPath: '/device/approve'
      preLoaderRoute: typeof DeviceDeviceApproveRouteImport
      parentRoute: typeof DeviceDeviceRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/accept/$invitationId': {
      id: '/orgs/accept/$invitationId'
      path: '/orgs/accept/$invitationId'
      fullPath: '/orgs/accept/$invitationId'
      preLoaderRoute: typeof OrgsAcceptInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/admin/clients/': {
      id: '/_dashboard/admin/clients/'
      path: '/clients'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof DashboardAdminClientsIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/clients/$id': {
      id: '/_dashboard/admin/clients/$id'
      path: '/clients/$id'
      fullPath: '/admin/clients/$id'
      preLoaderRoute: typeof DashboardAdminClientsIdRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/clients/new': {
      id: '/_dashboard/admin/clients/new'
      path: '/clients/new'
      fullPath: '/admin/clients/new'
      preLoaderRoute: typeof DashboardAdminClientsNewRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/orgs/': {
      id: '/_dashboard/admin/orgs/'
      path: '/orgs'
      fullPath: '/admin/orgs/'
      preLoaderRoute: typeof DashboardAdminOrgsIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/orgs/$id': {
      id: '/_dashboard/admin/orgs/$id'
      path: '/orgs/$id'
      fullPath: '/admin/orgs/$id'
      preLoaderRoute: typeof DashboardAdminOrgsIdRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/_dashboard/admin/orgs/new': {
      id: '/_dashboard/admin/orgs/new'
      path: '/orgs/new'
      fullPath: '/admin/orgs/new'
      preLoaderRoute: typeof DashboardAdminOrgsNewRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
  }
}

interface AuthRouteChildren {
  AuthConsentRoute: typeof AuthConsentRoute
  AuthPrivacyRoute: typeof AuthPrivacyRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthTermsRoute: typeof AuthTermsRoute
  AuthTwoFactorRoute: typeof AuthTwoFactorRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthConsentRoute: AuthConsentRoute,
  AuthPrivacyRoute: AuthPrivacyRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthTermsRoute: AuthTermsRoute,
  AuthTwoFactorRoute: AuthTwoFactorRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardAdminRouteChildren {
  DashboardAdminApiKeysRoute: typeof DashboardAdminApiKeysRoute
  DashboardAdminSessionsRoute: typeof DashboardAdminSessionsRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardAdminClientsIdRoute: typeof DashboardAdminClientsIdRoute
  DashboardAdminClientsNewRoute: typeof DashboardAdminClientsNewRoute
  DashboardAdminOrgsIdRoute: typeof DashboardAdminOrgsIdRoute
  DashboardAdminOrgsNewRoute: typeof DashboardAdminOrgsNewRoute
  DashboardAdminClientsIndexRoute: typeof DashboardAdminClientsIndexRoute
  DashboardAdminOrgsIndexRoute: typeof DashboardAdminOrgsIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminApiKeysRoute: DashboardAdminApiKeysRoute,
  DashboardAdminSessionsRoute: DashboardAdminSessionsRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardAdminClientsIdRoute: DashboardAdminClientsIdRoute,
  DashboardAdminClientsNewRoute: DashboardAdminClientsNewRoute,
  DashboardAdminOrgsIdRoute: DashboardAdminOrgsIdRoute,
  DashboardAdminOrgsNewRoute: DashboardAdminOrgsNewRoute,
  DashboardAdminClientsIndexRoute: DashboardAdminClientsIndexRoute,
  DashboardAdminOrgsIndexRoute: DashboardAdminOrgsIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardConnectionsRoute: typeof DashboardConnectionsRoute
  DashboardAccountApiKeysRoute: typeof DashboardAccountApiKeysRoute
  DashboardAccountPasskeysRoute: typeof DashboardAccountPasskeysRoute
  DashboardAccountProvidersRoute: typeof DashboardAccountProvidersRoute
  DashboardAccountSessionsRoute: typeof DashboardAccountSessionsRoute
  DashboardAccountIndexRoute: typeof DashboardAccountIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardConnectionsRoute: DashboardConnectionsRoute,
  DashboardAccountApiKeysRoute: DashboardAccountApiKeysRoute,
  DashboardAccountPasskeysRoute: DashboardAccountPasskeysRoute,
  DashboardAccountProvidersRoute: DashboardAccountProvidersRoute,
  DashboardAccountSessionsRoute: DashboardAccountSessionsRoute,
  DashboardAccountIndexRoute: DashboardAccountIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DeviceDeviceRouteChildren {
  DeviceDeviceApproveRoute: typeof DeviceDeviceApproveRoute
}

const DeviceDeviceRouteChildren: DeviceDeviceRouteChildren = {
  DeviceDeviceApproveRoute: DeviceDeviceApproveRoute,
}

const DeviceDeviceRouteWithChildren = DeviceDeviceRoute._addFileChildren(
  DeviceDeviceRouteChildren,
)

interface DeviceRouteChildren {
  DeviceDeviceRoute: typeof DeviceDeviceRouteWithChildren
}

const DeviceRouteChildren: DeviceRouteChildren = {
  DeviceDeviceRoute: DeviceDeviceRouteWithChildren,
}

const DeviceRouteWithChildren =
  DeviceRoute._addFileChildren(DeviceRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  DeviceRoute: DeviceRouteWithChildren,
  AboutRoute: AboutRoute,
  WelcomeRoute: WelcomeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  OrgsAcceptInvitationIdRoute: OrgsAcceptInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
