/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as IndexRouteImport } from './routes/index.tsx'
import { Route as OrdersIndexRouteImport } from './routes/orders.index.tsx'
import { Route as OrdersOrderNumberRouteImport } from './routes/orders.$orderNumber.tsx'
import { Route as ProductsIndexRouteImport } from './routes/products.index.tsx'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId.tsx'
import { Route as SettingsIndexRouteImport } from './routes/settings.index.tsx'
import { Route as StorefrontIndexRouteImport } from './routes/storefront.index.tsx'
import { Route as StorefrontSlugRouteImport } from './routes/storefront.$slug.tsx'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderNumberRoute = OrdersOrderNumberRouteImport.update({
  id: '/orders/$orderNumber',
  path: '/orders/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const StorefrontIndexRoute = StorefrontIndexRouteImport.update({
  id: '/storefront/',
  path: '/storefront/',
  getParentRoute: () => rootRouteImport,
} as any)
const StorefrontSlugRoute = StorefrontSlugRouteImport.update({
  id: '/storefront/$slug',
  path: '/storefront/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/orders/$orderNumber': typeof OrdersOrderNumberRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/storefront/$slug': typeof StorefrontSlugRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/storefront/': typeof StorefrontIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/orders/$orderNumber': typeof OrdersOrderNumberRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/storefront/$slug': typeof StorefrontSlugRoute
  '/orders': typeof OrdersIndexRoute
  '/products': typeof ProductsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/storefront': typeof StorefrontIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/orders/$orderNumber': typeof OrdersOrderNumberRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/storefront/$slug': typeof StorefrontSlugRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/storefront/': typeof StorefrontIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/orders/$orderNumber'
    | '/products/$productId'
    | '/storefront/$slug'
    | '/orders/'
    | '/products/'
    | '/settings/'
    | '/storefront/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/orders/$orderNumber'
    | '/products/$productId'
    | '/storefront/$slug'
    | '/orders'
    | '/products'
    | '/settings'
    | '/storefront'
  id:
    | '__root__'
    | '/'
    | '/orders/$orderNumber'
    | '/products/$productId'
    | '/storefront/$slug'
    | '/orders/'
    | '/products/'
    | '/settings/'
    | '/storefront/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrdersOrderNumberRoute: typeof OrdersOrderNumberRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  StorefrontSlugRoute: typeof StorefrontSlugRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  StorefrontIndexRoute: typeof StorefrontIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderNumber': {
      id: '/orders/$orderNumber'
      path: '/orders/$orderNumber'
      fullPath: '/orders/$orderNumber'
      preLoaderRoute: typeof OrdersOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storefront/': {
      id: '/storefront/'
      path: '/storefront'
      fullPath: '/storefront/'
      preLoaderRoute: typeof StorefrontIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storefront/$slug': {
      id: '/storefront/$slug'
      path: '/storefront/$slug'
      fullPath: '/storefront/$slug'
      preLoaderRoute: typeof StorefrontSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrdersOrderNumberRoute: OrdersOrderNumberRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  StorefrontSlugRoute: StorefrontSlugRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  StorefrontIndexRoute: StorefrontIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
